baseURL = 'https://arcadian.cloud/'
languageCode = 'en-us'
title = 'Arcadian Cloud'
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
uglyURLs = false

footnoteReturnLinkContents = "^"
searchHidden = false

# Theme specific examples
author = "Arcadian Cloud"
copyright = "Arcadian Cloud"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 6
theme = "PaperMod"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Arcadian Cloud"
  description = "Arcadian Cloud is a tech blog where I blog about issues or useful thoughts."
  images = ["logo.webp"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # Options: dark, light, auto
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["linkedin", "x", "reddit", "ycombinator"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

[assets]
  apple_touch_icon = "/icons/apple-touch-icon.png"
  safari_pinned_tab = "/icons/apple-touch-icon.png"

[label]
  text = "Home"
  icon = "/icons/apple-touch-icon.png"
  iconHeight = 35

[analytics.google]
  SiteVerificationTag = "XYZabc"

[fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10 # Search configuration for fuse.js

[menu]
  [[menu.main]]
    identifier = "Thought Leadership"
    name = "Thought Leadership"
    url = "/tags/thought-leadership/"
    weight = 10
    pre = "<i class='fas fa-heart'></i>"

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
    pre = "<i class='fas fa-folder'></i>"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
    pre = "<i class='fas fa-tags'></i>"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
   
[services]
  [services.googleAnalytics]
    ID = 'G-BE54252MEV'